# Generated by Django 5.0 on 2023-12-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=400)),
                ("category", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "store_id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("store_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "price_id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.product"
                    ),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.store"
                    ),
                ),
            ],
        ),
    ]
