# Generated by Django 5.0 on 2023-12-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="price",
            table="Price",
        ),
        migrations.AlterModelTable(
            name="product",
            table="Product",
        ),
        migrations.AlterModelTable(
            name="store",
            table="Store",
        ),
    ]
